export {default as Home} from './Home'
export {default as FnCounter} from './FnCounter'
export {default as ClassCounter} from './ClassCounter'
export {default as Input} from './Input'
export {default as BoxOfficeRanking} from './BoxOfficeRanking'
export {default as Covid19} from './Covid-19'
export {default as AirInfo} from './AirInfo'